import os
import smtplib
from email.message import EmailMessage
from pathlib import Path

from dotenv import load_dotenv


load_dotenv()


def get_email_settings():
    sender = os.getenv("EMAIL_SENDER")
    app_password = os.getenv("EMAIL_APP_PASSWORD")
    receiver = os.getenv("EMAIL_RECEIVER")

    if not sender:
        raise ValueError("EMAIL_SENDER is missing from .env")

    if not app_password:
        raise ValueError("EMAIL_APP_PASSWORD is missing from .env")

    if not receiver:
        raise ValueError("EMAIL_RECEIVER is missing from .env")

    return sender, app_password, receiver


def send_application(
    recruiter_email,
    company,
    role,
    location,
    applicant_name,
    resume_path,
    job_url,
    dry_run=True,
):
    sender, app_password, _ = get_email_settings()

    resume = Path(resume_path)

    if not resume.exists():
        raise FileNotFoundError(
            f"Resume not found: {resume}"
        )

    message = EmailMessage()

    message["Subject"] = (
        f"Application for {role} - {applicant_name}"
    )

    message["From"] = sender
    message["To"] = recruiter_email

    message.set_content(
        f"""Dear Hiring Team,

I am writing to apply for the {role} position at {company}.

I am a fresher with a background in Information Technology and
would be interested in an opportunity to contribute to your team.

Location: {location}

Please find my resume attached for your consideration.

Job reference:
{job_url}

Thank you for your time and consideration.

Regards,
{applicant_name}
"""
    )

    with open(resume, "rb") as file:
        message.add_attachment(
            file.read(),
            maintype="application",
            subtype="pdf",
            filename=resume.name,
        )

    if dry_run:
        print()
        print("DRY RUN - EMAIL NOT SENT")
        print(f"To      : {recruiter_email}")
        print(f"Company : {company}")
        print(f"Role    : {role}")
        print(f"Resume  : {resume}")
        return False

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(sender, app_password)
        smtp.send_message(message)

    print()
    print("APPLICATION EMAIL SENT")
    print(f"To      : {recruiter_email}")
    print(f"Company : {company}")
    print(f"Role    : {role}")

    return True


def send_application_confirmation(
    company,
    role,
    location,
    recruiter_email,
    job_url,
    status,
):
    sender, app_password, receiver = get_email_settings()

    message = EmailMessage()

    message["Subject"] = (
        f"Job Application Confirmation - {company}"
    )

    message["From"] = sender
    message["To"] = receiver

    message.set_content(
        f"""Job Application Confirmation

Your application has been sent.

Company       : {company}
Role          : {role}
Location      : {location}
Recruiter     : {recruiter_email}
Status        : {status}

Job URL:
{job_url}

This message was generated by JobAutomationBot.
"""
    )

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(sender, app_password)
        smtp.send_message(message)

    print("Confirmation email sent to you.")


def send_daily_summary(
    jobs_received,
    matching_jobs,
    new_jobs,
    applications_sent,
    daily_limit,
    errors=0,
):
    sender, app_password, receiver = get_email_settings()

    message = EmailMessage()

    message["Subject"] = "JobAutomationBot Daily Summary"
    message["From"] = sender
    message["To"] = receiver

    remaining = max(
        daily_limit - applications_sent,
        0,
    )

    message.set_content(
        f"""JobAutomationBot Daily Summary

Jobs received from source : {jobs_received}
Matching jobs             : {matching_jobs}
New jobs saved             : {new_jobs}
Applications sent today   : {applications_sent}
Daily application limit   : {applications_sent}/{daily_limit}
Remaining today           : {remaining}
Errors                    : {errors}

Bot status: COMPLETED
"""
    )

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(sender, app_password)
        smtp.send_message(message)

    print("Daily summary email sent to you.")